FROM node:22.18.0-bullseye

WORKDIR /app

COPY package.json pnpm-lock.yaml ./
COPY packages ./packages
COPY apps/container/package.json ./apps/container/
COPY apps/customers/package.json ./apps/customers/
COPY apps/selected/package.json ./apps/selected/

RUN corepack enable && corepack prepare pnpm@10.14.0 --activate
RUN pnpm install --frozen-lockfile

COPY . .

WORKDIR /app/apps/customers

EXPOSE 5001

CMD ["pnpm", "dev"]